###
#Requisição GET para listar todos

@host = https://cardlist-v1.herokuapp.com/
#@host = http://localhost:8080/
GET {{host}}

###
#Requisição GET para lsitar detalhes de 1 registro
GET {{host}}/informacoes/6

###
#Requisição POST para cadastrar um novo contato
POST {{host}}/cadastrar
Content-Type: application/json

{
    "nome": "Jinzo",
    "nivel": "6",
    "tipo": "Fiend",
    "pontos": "2400/1800"
}

###
#Requisição POST para editar um contato
POST {{host}}/adicionar
Content-Type: application/json

{
    "id": 11,
   "nome": "Jinzo",
    "nivel": "6",
    "tipo": "Fiend",
    "pontos": "2400/1800"
}